#
# Travis CI configuration for nodeGaudi
#

# This is a Node.js project; test against Node.js 0.11 and 0.10.
language: node_js
node_js:
  - "0.11"
  - "0.10"

# Use `g++` for compiling HelloWorld C++ example.
compiler: g++
# Use `rake travis` to test.
script: rake travis
