#
# Travis CI configuration for nodeGaudi
#

# This is a Node.js project; test against Node.js 0.10.
# CSON module seems to be incompatible with 0.11.
language: node_js
node_js:
  - "0.10"

# Use `g++` for compiling HelloWorld C++ example.
compiler: g++
install: g++ --version

# Get dependencies via `npm install` and then invoke nodeGaudi itself to test functionality.
before_script: npm install
script: ./nodeGaudi -f build.cson test
